### ISSUE TITLE
BUG ChangeHmac

### ISSUE THREAD

**Issue by bindermartin** [derhansen/fe_change_pwd#35] opened 2020-03-05 12:44 UTC
Hello,

I've got the following bug when I want to change my password:

Exception while property mapping at property path "": It is not allowed to map property "changeHmac". You need to use $propertyMappingConfiguration->allowProperties('changeHmac') to enable mapping of this property.

Is this an already known problem and how can it be solved?

**Comment by derhansen** [comment] 2020-03-05 12:53
Did you just upgrade the extension to a new version? If yes, please make sure you clear the full cache including Composer Autoload files, since the mentioned field is new in version 1.5.0

**Comment by bindermartin** [comment] 2020-03-05 13:06
Yes, I have cleared the full cache including PHP Autoload Information.
I found that issue in my installed version 1.5.0. After that I thought I could update the extension to the newest version 2.0.0. Unfortunately nothing has changed.

I've the following settings in my Typoscript:
plugin.tx_fechangepwd.view.templateRootPaths = EXT:theme_gugler_bootstrap_ecoplus/Resources/Private/Extensions/fe_change_pwd/Templates/
plugin.tx_fechangepwd.settings.requireCurrentPassword.enabled = 1
plugin.tx_fechangepwd.settings.changePasswordPid = 206

If I change my overriden template back to the origin template code, typo3 also shows the same problem.

**Comment by derhansen** [comment] 2020-03-05 13:33
Sorry, I can not reproduce the problem either on TYPO3 9.5 nor on the latest V10. 

* I installed it on a fresh TYPO3 9.5 instance and could change the password of the fe_user without the mentioned problem. 
* I tested it on TYPO3 10 (master) without any problems.

So I think, the problem must be related to your site/setup somewhere. If you extended the extension (XClass / Signal slots) please try to undo you changes. Also try to use the default templates first before using your own template. Hope this helps you to resolve the problem.

**Comment by bindermartin** [comment] 2020-03-10 13:49
Unfortunately I haven't solved the problem yet. We are running Typo3 9.5.11 and we haven't extended the extension either. It seems like a bug from the extension.
![Bildschirmfoto 2020-03-10 um 14 41 56](https://user-images.githubusercontent.com/60733494/76318619-464dff80-62de-11ea-90cb-1f6b526859fb.png)

**Comment by derhansen** [comment] 2020-03-10 14:12
As said, I can not reproduce the problem and tested it locally on V9 and V10 without any problems. Also I maintain several TYPO3 websites, where the extension is used in production out of the box without any modifications to its original state from TER or packagist without the mentioned error message.

Last things you could try is to:

* Completely remove the extension from the system (make sure, all files in `typo3conf/ext/fe_change_pwd` are removed) and reinstall it from TER/packagist
* Try to reproduce the same problem in another or fresh TYPO3 website. If the same problem occurs there, please contact me

**Comment by derhansen** [comment] 2020-05-27 08:51
I'm closing this issue now. Feel free to reopen it, if you believe the problem is related to the extension.

**Closed by derhansen** 2020-05-27 08:51 UTC

**Comment by bindermartin** [comment] 2020-06-16 11:55
Hello,

i think I finally solved the problem. I've added those 4 lines into the initializeUpdateAction of the PasswordController and now it works! But I think there will be problems updating the extension in the future. Do you know how to solve this problem in the future too?

$propertyMappingConfiguration = $this->arguments['changePassword']->getPropertyMappingConfiguration();
$propertyMappingConfiguration->allowAllProperties();
$propertyMappingConfiguration>setTypeConverterOption('TYPO3\CMS\Extbase\Property\TypeConverter\PersistentObjectConverter', \TYPO3\CMS\Extbase\Property\TypeConverter\PersistentObjectConverter::CONFIGURATION_CREATION_ALLOWED, TRUE);

Kind Regards
Martin

**Comment by derhansen** [comment] 2020-06-16 12:10
Since the problem is not reproducible to me and this is the only report about such a problem, I still believe this has something to do with your local setup. Therefore I can not give you any hints on how you can resolve the problem for your TYPO3 website in the future.

If I should help/investigate here, please provide information on how to reproduce the problem on a fresh TYPO3 installation (only minimal setup - simple template and no CSS is OK).
