### ISSUE TITLE
Old Password check will always fail in 3.0.1

### ISSUE THREAD

**Issue by mnediw** [derhansen/fe_change_pwd#59] opened 2022-09-27 09:22 UTC
In OldPasswordService::checkEqualsOldPassword you try to check if the provided *old* pw fits the user's pw. 

But what you really do is to check the *new* password:
/fe_change_pwd/Classes/Service/OldPasswordService.php:38
($changePassword->getPassword1() instead of  $changePassword->getCurrentPassword())

The problem came with this commit:
https://github.com/derhansen/fe_change_pwd/commit/725a8f2e6ad86b4842eba106685374c9a34806a5#diff-9dfd257b1c359333ba0eb65e99d56dab1327bba65477cdf982ce67835c561a3a

**Comment by derhansen** [comment] 2022-09-27 17:59
Thanks, nice catch! I did not have in mind, that the function is currently used in 3 different scopes with 2 different passwords to check. The problem is fixed in version 3.0.2, which just has been released.

**Closed by derhansen** 2022-09-27 17:59 UTC
